### ISSUE TITLE
Add functional test to OpenDroneMap transformer using CI

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#28]
**Task to do**
Add testing to OpenDroneMap transformer for quality check for master, develop, and pull requests

**Reason**
Better transformers

**Result**
Testing occurs for master, develop, and PR changes

**Steps to take**
- [ ] Identify dataset for testing
- [ ] Build and run OpenDroneMap transformer
- [ ] Ensure results are correct
