### ISSUE TITLE
Create github workflow to publish agpypeline to Pypi

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#66]
**Task to do**
After successful merge with master branch, automatically publish new library

**Reason**
Provides automatic update for the library

**Result**
The latest library is available to users

**Starting requirements**
It's expected that merges to the `master` branch will have passed all tests

**Expected operation**
- [x] Uses GitHub actions and/or workflows
- [x] Publishing step is automatically started after successful merge to `master` branch
- [x] Build library is automatically assigned a new version number using standard versioning convention
- [x] Built library is published

**Comment by Chris-Schnaufer** [comment]
Reverting to in progress since it's not working yet
