### ISSUE TITLE
Try out OpenDroneMap v1.0.0

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#71]
**Task to do**
Base transformer-opendronemap off of ODM v1.0.0

**Reason**
Check for an upgrade in quality of products

**Result**
Decision to move to v1.0.0 or remain on current version

**Steps to take**
- [x] Build test transformer-opendronemap instance
- [x] run transformer against large dataset that was previously generated
- [x] compare resulting products for improved quality and accuracy
- [x] note issues and concerns with using new version
- [x] determine if using new version is warranted (and write new issue if it is)

**Comment by Chris-Schnaufer** [comment]
There doesn't appear to be any significant improvements to be gained by using v1.0.0 for our purposes.

No issues or concerns: appears to work as well as our current version
