### ISSUE TITLE
Default missing Species name values when not available

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#73]
**Task to do**
If a species name is not specified by the user of the pipeline, replace with a default value

**Reason**
Not requiring users to have all data available when running the pipeline

**Result**
A default species name value is used when it's missing

**Affected Transformers**
- [x] canopy cover
- [x] rgb plot template
- [x] other (investigate other places it may be used and add found locations to comments)

**Comment by Chris-Schnaufer** [comment]
- [x] Canopy cover defaults to 'Unknown' already
- [x] RGB plot template supporting code (plot-base-rgb) default to 'Unknown' [the code template doesn't specify or use species directly]
- [x] there are no other repositories that need to be updated [the Lidar repositories aren't supported yet]
