### ISSUE TITLE
Investigate and default Collecting site name when it's not specified

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#74]
**Task to do**
Replace missing Collecting site name with a default value

**Reason**
Not require users to specify values to use the pipeline

**Result**
If missing, the Collecting site name is defaulted to a value and an warning issues

**Steps to take**
- [x] Determine what transformers use this value
- [ ] ~Document found transformers in this ticket using comments~
- [ ] ~Update the code to default the value to something meaningful~

**Comment by Chris-Schnaufer** [comment]
This value doesn't appear to be used by any Transformer
