### ISSUE TITLE
SciF: have recipes pull from GitHub tags directly

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#77]
**Task to do**
Change the SciF recipes to pull directly from GitHub by tag name

**Reason**
Currently the source code files to install for transformers are pulled from a manually created .tar.gz file stored somewhere on the network/internet. This is fraught with issues including uncertainty as to what version of code is included in a SciF Docker image. By pulling tagged archives from GitHub directly the provenance of the files used is clear

**Result**
The SciF recipes pull directly from GitHub

**Recipes affected**
- [ ] canopycover_v0.0.1_ubuntu16.04.scif
- [ ] plotclip_v0.0.1_ubuntu16.04.scif
- [ ] soilmask_v0.0.1_ubuntu16.04.scif

The OpenDroneMap (ODM) recipe is not part of this issue at this time. If the concerns surrounding ODM are resolved, it can be included in this issue

**Completion criteria**
- [ ] each recipe identified above pulls from GitHub
- [ ] the SciF docker image is successfully built
- [ ] the newly built SciF docker image can run through to completion

**Comment by Chris-Schnaufer** [comment]
Tagged versions in github:
canopycover: https://github.com/AgPipeline/transformer-canopycover/releases/tag/v1.1
plotclip: https://github.com/AgPipeline/transformer-plotclip/releases/tag/v2.2
soilmask: https://github.com/AgPipeline/transformer-soilmask/releases/tag/v2.1

The archives of these tagged versions are to be used instead of what's there now

**Comment by jvanderleeuw** [comment]
Github issue: https://github.com/AgPipeline/drone-makeflow/pull/15
