### ISSUE TITLE
Update template repos to use AgPypeline

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#78]
**Task to do**
The AgPypeline library is newly available and the code templates need to be updated to use it

**Reason**
The AgPypeline simplifies Transformer development and maintenance and the templates should be updated to use it to keep up to date with the latest changes

**Result**
Updated template repos

**Repositories impacted**
- [x] plot-base-rgb
- [x] template-plot-rgb
- [x] template-transformer-simple

**Comment by Chris-Schnaufer** [comment]
plot_base_rgb repo: https://github.com/AgPipeline/plot-base-rgb/pull/3
template-plot-rgb: https://github.com/AgPipeline/template-rgb-plot/pull/9
template-transformer-simple: https://github.com/AgPipeline/template-transformer-simple/pull/17

**Comment by Chris-Schnaufer** [comment]
Created following issues for reviewing the changes:
https://github.com/AgPipeline/issues-and-projects/issues/193
https://github.com/AgPipeline/issues-and-projects/issues/194
https://github.com/AgPipeline/issues-and-projects/issues/195
